#set_property PACKAGE_PIN P17 [get_ports clk] 
#set_property PACKAGE_PIN G2 [get_ports {sm_wei[0]}] 
#set_property PACKAGE_PIN C2 [get_ports {sm_wei[1]}] 
#set_property PACKAGE_PIN C1 [get_ports {sm_wei[2]}] 
#set_property PACKAGE_PIN H1 [get_ports {sm_wei[3]}] 
#set_property PACKAGE_PIN B4 [get_ports {sm_duan[0]}]
#set_property PACKAGE_PIN A4 [get_ports {sm_duan[1]}] 
#set_property PACKAGE_PIN A3 [get_ports {sm_duan[2]}] 
#set_property PACKAGE_PIN B1 [get_ports {sm_duan[3]}] 
#set_property PACKAGE_PIN A1 [get_ports {sm_duan[4]}] 
#set_property PACKAGE_PIN B3 [get_ports {sm_duan[5]}] 
#set_property PACKAGE_PIN B2 [get_ports {sm_duan[6]}] 
#set_property PACKAGE_PIN D5 [get_ports {sm_duan[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports clk] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_wei[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[0]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[1]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[2]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[3]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[4]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[5]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[6]}] 
#set_property IOSTANDARD LVCMOS33 [get_ports {sm_duan[7]}]

#set_property PACKAGE_PIN R2 [get_ports {scorein[3]}]
#set_property PACKAGE_PIN M4 [get_ports {scorein[2]}]
#set_property PACKAGE_PIN N4 [get_ports {scorein[1]}]
#set_property PACKAGE_PIN R1 [get_ports {scorein[0]}]


#set_property IOSTANDARD LVCMOS33 [get_ports {scorein[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {scorein[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {scorein[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {scorein[0]}]

#set_property PACKAGE_PIN P17 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]

#set_property PACKAGE_PIN R11 [get_ports submit]
#set_property IOSTANDARD LVCMOS33 [get_ports submit]

##set_property PACKAGE_PIN B4 [get_ports {sm_duan[0]}]
##set_property PACKAGE_PIN A4 [get_ports {sm_duan[1]}] 
##set_property PACKAGE_PIN A3 [get_ports {sm_duan[2]}] 
##set_property PACKAGE_PIN B1 [get_ports {sm_duan[3]}] 
##set_property PACKAGE_PIN A1 [get_ports {sm_duan[4]}] 
##set_property PACKAGE_PIN B3 [get_ports {sm_duan[5]}] 
##set_property PACKAGE_PIN B2 [get_ports {sm_duan[6]}] 
##set_property PACKAGE_PIN D5 [get_ports {sm_duan[7]}]

#set_property PACKAGE_PIN D5 [get_ports {seg[7]}]
#set_property PACKAGE_PIN B2 [get_ports {seg[0]}]
#set_property PACKAGE_PIN B3 [get_ports {seg[1]}]
#set_property PACKAGE_PIN A1 [get_ports {seg[2]}]
#set_property PACKAGE_PIN B1 [get_ports {seg[3]}]
#set_property PACKAGE_PIN A3 [get_ports {seg[4]}]
#set_property PACKAGE_PIN A4 [get_ports {seg[5]}]
#set_property PACKAGE_PIN B4 [get_ports {seg[6]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

##set_property PACKAGE_PIN G2 [get_ports {sm_wei[0]}] 
##set_property PACKAGE_PIN C2 [get_ports {sm_wei[1]}] 

#set_property PACKAGE_PIN C2 [get_ports {sel[1]}]
#set_property PACKAGE_PIN G2 [get_ports {sel[0]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]


set_property PACKAGE_PIN R11 [get_ports turn]
set_property IOSTANDARD LVCMOS33 [get_ports turn]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN P15 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN K3 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports led]

set_property PACKAGE_PIN D5 [get_ports {seg[7]}]
set_property PACKAGE_PIN B4 [get_ports {seg[6]}]
set_property PACKAGE_PIN A4 [get_ports {seg[5]}]
set_property PACKAGE_PIN A3 [get_ports {seg[4]}]
set_property PACKAGE_PIN B1 [get_ports {seg[3]}]
set_property PACKAGE_PIN A1 [get_ports {seg[2]}]
set_property PACKAGE_PIN B3 [get_ports {seg[1]}]
set_property PACKAGE_PIN B2 [get_ports {seg[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]

set_property PACKAGE_PIN C1 [get_ports {sel[3]}]
set_property PACKAGE_PIN H1 [get_ports {sel[2]}]
set_property PACKAGE_PIN G2 [get_ports {sel[1]}]
set_property PACKAGE_PIN C2 [get_ports {sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sel[0]}]